# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc48d69612cf22bffef10c7705b0fd2378aaf6ca7d2b3fbf433423a04b0bd568f741e900bcbd273015a49a7acfb8b22896864dec58c0de1e65b7c0660e79af91

test:
  secret_key_base: 16ed4f49be0b0c518a475bd7d94f5f03d09c02edfb457ae95e9ea29352cef74b2048733d391ef1ab36f732016def551c68e3978513cab334f482b0db6a029f1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
